version: "3.8"

services:
  rabbitmq1:
    image: rabbitmq:3.13.1-management-alpine
    hostname: rabbitmq1
    container_name: rabbitmq1
    restart: always
    ports:
      - 25672:5672
      - 35672:15672
    volumes:
      - ./SERVICE_DATA/appdata/rabbitmq1/data/:/var/lib/rabbitmq/
      - ./SERVICE_DATA/appdata/rabbitmq1/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    logging:
      options:
        max-size: "50m"

  rabbitmq2:
    image: rabbitmq:3.13.1-management-alpine
    hostname: rabbitmq2
    container_name: rabbitmq2
    restart: always
    ports:
      - 25673:5672
      - 35673:15672
    volumes:
      - ./SERVICE_DATA/appdata/rabbitmq2/data/:/var/lib/rabbitmq/
      - ./SERVICE_DATA/appdata/rabbitmq2/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq1
    logging:
      options:
        max-size: "50m"

  rabbitmq3:
    image: rabbitmq:3.13.1-management-alpine
    hostname: rabbitmq3
    container_name: rabbitmq3
    restart: always
    ports:
      - 25674:5672
      - 35674:15672
    volumes:
      - ./SERVICE_DATA/appdata/rabbitmq3/data/:/var/lib/rabbitmq/
      - ./SERVICE_DATA/appdata/rabbitmq3/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq1
    logging:
      options:
        max-size: "50m"

networks:
  rabbitmq_network:
    driver: bridge
